version: "3.2"

services:
  mysql:
    image: mysql:5.7
    env_file:
      - ../auth-service/env/.env.dev
    ports:
      - 3306:3306
    volumes:
      - ../auth-service/mysql_data:/var/lib/mysql
  app:
    build: ../auth-service
    env_file:
      - ../auth-service/env/.env.dev
    volumes:
      - ../auth-service/:/app
      - ../auth-service/static_data:/srv/static
    depends_on:
      - mysql
    expose:
      - 8000
  nginx:
    build: ../auth-service/config/nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ../auth-service/mysql_data:/var/lib/mysql
      - ../auth-service/static_data:/srv/static:ro  # ro readonly
  angular:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - app
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "4200:4200"
